package GameServer;

/**
* GameServer/CrowdedRoomHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameManagerIDL.idl
* Quarta-feira, 28 de Junho de 2017 00h39min39s BRT
*/

public final class CrowdedRoomHolder implements org.omg.CORBA.portable.Streamable
{
  public GameServer.CrowdedRoom value = null;

  public CrowdedRoomHolder ()
  {
  }

  public CrowdedRoomHolder (GameServer.CrowdedRoom initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameServer.CrowdedRoomHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameServer.CrowdedRoomHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameServer.CrowdedRoomHelper.type ();
  }

}
