package GameServer;


/**
* GameServer/CrowdedRoom.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameManagerIDL.idl
* Quarta-feira, 28 de Junho de 2017 00h39min39s BRT
*/

public final class CrowdedRoom extends org.omg.CORBA.UserException
{

  public CrowdedRoom ()
  {
    super(CrowdedRoomHelper.id());
  } // ctor


  public CrowdedRoom (String $reason)
  {
    super(CrowdedRoomHelper.id() + "  " + $reason);
  } // ctor

} // class CrowdedRoom
