package GameServer;


/**
* GameServer/GameManagerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameManagerIDL.idl
* Quarta-feira, 28 de Junho de 2017 00h39min39s BRT
*/

public interface GameManagerOperations 
{
  GameServer.Player enterOnMatch (GameServer.ServerListener listener) throws GameServer.CrowdedRoom;
  void leaveMatch (String playerName);
  GameServer.Player currentPlayer ();
  void startNewTurn ();
  void finishTurnOf (String playerName, int rightHandPicks, int turnShot);
  boolean isAValidTurnShot (String playerName, int shot);
  GameServer.Player playerData (String playerName);
  GameServer.Player[] playersInfo ();
} // interface GameManagerOperations
