package GameServer;

/**
* GameServer/GameManagerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameManagerIDL.idl
* Quarta-feira, 28 de Junho de 2017 00h39min39s BRT
*/

public final class GameManagerHolder implements org.omg.CORBA.portable.Streamable
{
  public GameServer.GameManager value = null;

  public GameManagerHolder ()
  {
  }

  public GameManagerHolder (GameServer.GameManager initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameServer.GameManagerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameServer.GameManagerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameServer.GameManagerHelper.type ();
  }

}
