package GameServer;


/**
* GameServer/PlayersHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameManagerIDL.idl
* Quarta-feira, 28 de Junho de 2017 00h39min39s BRT
*/

public final class PlayersHolder implements org.omg.CORBA.portable.Streamable
{
  public GameServer.Player value[] = null;

  public PlayersHolder ()
  {
  }

  public PlayersHolder (GameServer.Player[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameServer.PlayersHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameServer.PlayersHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameServer.PlayersHelper.type ();
  }

}
