package GameServer;


/**
* GameServer/PlayersHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameManagerIDL.idl
* Quarta-feira, 28 de Junho de 2017 00h39min39s BRT
*/

abstract public class PlayersHelper
{
  private static String  _id = "IDL:GameServer/Players:1.0";

  public static void insert (org.omg.CORBA.Any a, GameServer.Player[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static GameServer.Player[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = GameServer.PlayerHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (GameServer.PlayersHelper.id (), "Players", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static GameServer.Player[] read (org.omg.CORBA.portable.InputStream istream)
  {
    GameServer.Player value[] = null;
    int _len0 = istream.read_long ();
    value = new GameServer.Player[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = GameServer.PlayerHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, GameServer.Player[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      GameServer.PlayerHelper.write (ostream, value[_i0]);
  }

}
