package GameServer;

/**
* GameServer/PlayerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameManagerIDL.idl
* Quarta-feira, 28 de Junho de 2017 00h39min39s BRT
*/

public final class PlayerHolder implements org.omg.CORBA.portable.Streamable
{
  public GameServer.Player value = null;

  public PlayerHolder ()
  {
  }

  public PlayerHolder (GameServer.Player initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameServer.PlayerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameServer.PlayerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameServer.PlayerHelper.type ();
  }

}
