package GameServer;

/**
* GameServer/ServerListenerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameManagerIDL.idl
* Quarta-feira, 28 de Junho de 2017 00h39min39s BRT
*/

public final class ServerListenerHolder implements org.omg.CORBA.portable.Streamable
{
  public GameServer.ServerListener value = null;

  public ServerListenerHolder ()
  {
  }

  public ServerListenerHolder (GameServer.ServerListener initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameServer.ServerListenerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameServer.ServerListenerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameServer.ServerListenerHelper.type ();
  }

}
