package GameServer;


/**
* GameServer/ServerListenerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameManagerIDL.idl
* Quarta-feira, 28 de Junho de 2017 00h39min39s BRT
*/

public interface ServerListenerOperations 
{
  void newPlayerOnMatch (GameServer.Player player, GameServer.Player[] allPlayers);
  void showUpdatesOfPlayers (GameServer.Player[] players);
  void startOfTurn (GameServer.Player[] players);
  void endOfTurn (GameServer.Player[] playersOnMatch, GameServer.Player[] winners, String turnWinnerName);
  void gameOver (GameServer.Player[] winners, GameServer.Player loser);
  void connectionLost (String playerName, GameServer.Player[] players);
  void playerLeavingMatch (String playerName, GameServer.Player[] players);
} // interface ServerListenerOperations
