package GameServer;


/**
* GameServer/ServerListenerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameManagerIDL.idl
* Quarta-feira, 28 de Junho de 2017 00h39min39s BRT
*/

abstract public class ServerListenerHelper
{
  private static String  _id = "IDL:GameServer/ServerListener:1.0";

  public static void insert (org.omg.CORBA.Any a, GameServer.ServerListener that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static GameServer.ServerListener extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (GameServer.ServerListenerHelper.id (), "ServerListener");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static GameServer.ServerListener read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ServerListenerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, GameServer.ServerListener value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static GameServer.ServerListener narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof GameServer.ServerListener)
      return (GameServer.ServerListener)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      GameServer._ServerListenerStub stub = new GameServer._ServerListenerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static GameServer.ServerListener unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof GameServer.ServerListener)
      return (GameServer.ServerListener)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      GameServer._ServerListenerStub stub = new GameServer._ServerListenerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
